name: EC2 SSH Connection

on:
  push:
    branches: [master]

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Optionally skip host key check (for now)
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          # Simple test to verify connection
          ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST 'echo "Successfully connected to EC2 instance $(hostname)"'
